# Get Companies
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

query {
  items {
    id
    name,
    native_name 
  } 
}

### Create Item
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  createItem( 
    title: "Test Item",    
    native_title: "Native Test Item", 
    unit_price: 220,
    cost_price: 100,
    sell_price: 100,
  ){
    id,
    title, 
    unit_price,
    cost_price,
    sell_price,
  }
}


### Update Item
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  updateItem(
    id: 1,
    categoryParams: { 
      name: "Update Item", 
    }
  ){
    id,
    name, 
  }
}

