# Get Item
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

query {
  items {
    id
    title,
    nativeTitle
  } 
}

### Create Item
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  createItem( 
    title: "Test Item",     
    unitPrice: 220,
    costPrice: 100,
    sellPrice: 100, 
    shopId: 1,
    categoryIds: [{ categoryId: 1},{ categoryId: 2}]
  ){
    id,
    title, 
    unitPrice,
    costPrice,
    sellPrice,
    shopId
  }
}

### Update Item
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  updateItem(
    id: 1,
    itemParams: { 
      title: "Update Item", 
    }
  ){
    id,
    title, 
  }
}

