# Get Product
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

query {
  products {
    id
    title,
    nativeTitle
  } 
}

### Create Product
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation {
  createProduct(
    typeId: 5,
    item: {
      title: "Test Item", 
      unitPrice: 220, 
      costPrice: 100, 
      sellPrice: 100,  
    }, 
    hasVariant: [
      {
        variantId: 1, 
        variantValueId: 1, 
        unitPrice: 220, 
        costPrice: 100, 
        sellPrice: 100,  
      },
      {
        variantId: 1, 
        variantValueId: 2, 
        unitPrice: 240, 
        costPrice: 130, 
        sellPrice: 100,  
      },
    ], 
    brandId: 3
    categoryIds: [ {categoryId: 4}]
    ) {
    id
    title 
    item {
      title 
    }
  }
}


### Update Product
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  updateProduct(
    id: 1,
    itemParams: { 
      title: "Update Product", 
    }
  ){
    id,
    title, 
  }
}

