# Get Companies
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

query {
  companies {
    id
    name, 
  } 
}

### Create Company
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  createCompany( 
    name: "Oxyzone",  
  ){
    id,
    name,
  }
}


### Update Company
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  updateCompany(
    id: 1,
    companyParams: {
        goldenSupplier: false,
        highestAssurance: null,
        isActive: false,
        isVerifed: false,
        name: "Oxyzone",
        tradeAssurance: false, 
        locationId: null,
        attachmentId: null,
        term_conditionId: null, 
    }
  ){
    id,
    name, 
  }
}

