

### Get shop all
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

query {
  shops {
    id
    name,
    nativeName 
  } 
}

### Get shop

POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}
query{
  shop(id:1){
    id
    name
    nativeName,
    isActive,
    locationId,
    userId,
    locationId
  }
}


### Create Shop
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  createShop( 
    name: "Mini Bazar",  
    companyId: 1
  ){
    id,
    name, 
  }
}


### Update Shop
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  updateShop(
    id: 1,
    shopParams: {
        goldenSupplier: false,
        highestAssurance: null,
        isActive: false,
        isVerifed: false,
        name: "Mini Bazaar",
        tradeAssurance: false, 
        locationId: null,
        attachmentId: null,
        term_conditionId: null, 
    }
  ){
    id,
    name, 
  }
}

