### Get all Warehouse
POST http://{{host}}:{{port}}{{url}}
Authorization: {{ user_token }}

query {
  warehouses{
    id
    name
    nativeName
    isActive
    locationId
    shopId
    userId
  }
}


### GET Warehouse
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

query{
  warehouse(id:1){
    id
    name
    nativeName
    isActive
    locationId
    shopId
    userId
    locationId
  }
}

### Create Warehouse
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  createWarehouse(name:"test",nativeName:"test",shopId:5,){
    id
    name
    nativeName
    isActive
    locationId
    shopId
    userId
    locationId
  }
}


### Update Warehouse
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  updateWarehouse(id:1,warehouseParams:{name:"gest",nativeName:"test",shopId:1,userId:1}){
    id
    name
    nativeName
    isActive
    locationId
    shopId
    userId
    locationId
  }
}
