# Get Brands
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}
 
{
  brands(first: 5, filter: {id: 3}) {
    pageInfo{
      hasPreviousPage
      hasNextPage
      endCursor
      startCursor
    }
    edges{
      node{
        id
        name,
        nativeName
      }
      cursor 
    }
  }
}

### Create Brand
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  createBrand( 
    name: "RFL",  
    nativeName: "আর আফ এল",  
    categoryIds: [{categoryId: 1}, {categoryId: 3}]
  ){
    id,
    name, 
    slug,
    userId
  }
}


### Update Brand
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  updateBrand(
    id: 1,
    brandParams: { 
      name: "Update Brand", 
    }
  ){
    id,
    name, 
  }
}

### Delete Brand
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  deleteBrand(
    id: 2, 
  ){
    id,
    name, 
  }
}
