# Get Companies
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

query {
  categories {
    id
    name,
    nativeName 
  } 
}

### Create Category
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  createCategory( 
    name: "Test Category",   
    slug: "test-cat",
    nativeName: "Native Test Category", 
  ){
    id,
    name, 
  }
}


### Update Category
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  updateCategory(
    id: 1,
    categoryParams: { 
      name: "Update Category", 
    }
  ){
    id,
    name, 
  }
}

