# Get Categories
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

{
  categories(first: 5, filter: {}) {
    pageInfo{
      hasPreviousPage
      hasNextPage
      endCursor
      startCursor
    }
    edges{
      node{
        id
        name,
        nativeName
      }
      cursor 
    }
  }
}

### Create Category
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  createCategory( 
    name: "Fruits",  
    nativeName: "ফল",  
  ){
    id,
    name, 
    slug,
    userId
  }
}


### Update Category
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  updateCategory(
    id: 1,
    categoryParams: { 
      name: "Update Category", 
    }
  ){
    id,
    name, 
  }
}

### Delete Category
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  deleteCategory(
    id: 1, 
  ){
    id,
    name, 
  }
}
