# Get PackageItems

POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

query {
  packageItems {
    id
    question,
    nativeQuestion 
  } 
}

### Create PackageItem
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  createPackageItem(
    name: "PackageItem Name"
    nativeName: "PackageItem Native Name" 
    packageId: 3
  ) {
    id
    name
    nativeName 
  }
}

### Update PackageItem
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  updatePackageItem(
    id: 1,
    packageParams: { 
      name: "Update PackageItem", 
    }
  ){
    id,
    name, 
  }
}

