# Get Variants
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

{
  variants(first: 5, filter: {variant_id: 1}) {
    pageInfo{
      hasPreviousPage
      hasNextPage
      endCursor
      startCursor
    }
    edges{
      node{
        id
        name,
        nativeName
      }
      cursor 
    }
  }
}

### Create Variant
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  createVariant( 
    name: "Color",  
    nativeName: "রং", 
    type: 1,
    categoryIds: [{categoryId: 1}, {categoryId: 3}]
  ){
    id,
    name,  
    userId
  }
}


### Update Variant
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  updateVariant(
    id: 1,
    variantParams: { 
      name: "Update Variant", 
    }
  ){
    id,
    name, 
  }
}

### Delete Variant
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  deleteVariant(
    id: 1, 
  ){
    id,
    name, 
  }
}
