# Get VariantValues
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

{
  variantValues(first: 5, filter: {variant_id: 1}) {
    pageInfo{
      hasPreviousPage
      hasNextPage
      endCursor
      startCursor
    }
    edges{
      node{
        id
        name,
        nativeName
      }
      cursor 
    }
  }
}

### Create VariantValue
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  createVariantValue( 
    variantId: 1,
    name: "Red",  
    nativeName: "লাল",   
  ){
    id,
    name,  
    userId
  }
}


### Update VariantValue
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  updateVariantValue(
    id: 1,
    variantParams: { 
      name: "Update VariantValue", 
    }
  ){
    id,
    name, 
  }
}

### Delete VariantValue
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  deleteVariantValue(
    id: 1, 
  ){
    id,
    name, 
  }
}
