# Get Attachments
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

query {
  attachments {
    id,
    orginalSize
    resizedSize 
  } 
}

### Create Attachment
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  createAttachment(
    type: 1,
    typeId: 2,
    fileName: "test",
    orginalSize: "image.jpg",
    resizedSize: "image100x100.jpg", 
  ){
    id,
    orginalSize
    resizedSize
  }
}

