### Get Users 
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

{
  users(first: 5, filter: {}) {
    pageInfo{
      hasPreviousPage
      hasNextPage
      endCursor
      startCursor
    }
    edges{
      node{
        firstName
      }
      cursor 
    }
  }
}

### Get User
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

query{
  user (id:1){
    id
  }
}



### Create User
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  createUser(
    surname: "test",
    firstName: "test",
    mobile: "0123456789",
    email: "example@example.com",
    pin: 12345678,
    password: "1234567a",
    passwordConfirmation: "1234567a"
  ){
    id,
    firstName,
    surname, 
    mobile,
    email,
    verifiedUser,
  }
}


### Update User
POST http://{{host}}:{{port}}{{url}}
Authorization: {{user_token}}

mutation{
  updateUser(
    id: 4,
    userParams: { 
    mobile: "880123456789", 
    }
  ){
    id,
    firstName,
    surname, 
    mobile,
    email
  }
}
